package config

import (
	"fmt"
	"reflect"
	"sort"
	"strings"
	"time"
)

// ExampleYAML renders the fully-commented reference configuration from the
// Config struct tags and defaults, so the reference can never drift from the
// real config surface.
func ExampleYAML() string {
	var b strings.Builder
	b.WriteString("# pdbq reference configuration.\n")
	b.WriteString("# Generated by `pdbq config example` from the config structs — reference, not for direct use.\n")
	b.WriteString("# Every key is also settable via env (PDBQ_SECTION_KEY, double underscore for '_' in names)\n")
	b.WriteString("# or command-line flags; precedence is flags > env > file.\n\n")
	writeStruct(&b, reflect.ValueOf(DefaultConfig()), 0)
	return b.String()
}

func writeStruct(b *strings.Builder, v reflect.Value, indent int) {
	t := v.Type()
	pad := strings.Repeat("  ", indent)
	for i := 0; i < t.NumField(); i++ {
		f := t.Field(i)
		key := f.Tag.Get("koanf")
		if key == "" || key == "-" {
			continue
		}
		doc := f.Tag.Get("doc")
		fv := v.Field(i)
		if fv.Kind() == reflect.Struct && f.Type != reflect.TypeOf(time.Duration(0)) {
			if doc != "" {
				fmt.Fprintf(b, "%s# %s\n", pad, doc)
			}
			fmt.Fprintf(b, "%s%s:\n", pad, key)
			writeStruct(b, fv, indent+1)
			if indent == 0 {
				b.WriteString("\n")
			}
			continue
		}
		if doc != "" {
			fmt.Fprintf(b, "%s# %s\n", pad, doc)
		}
		fmt.Fprintf(b, "%s%s: %s\n", pad, key, yamlValue(fv))
	}
}

func yamlValue(v reflect.Value) string {
	switch v.Kind() {
	case reflect.String:
		return fmt.Sprintf("%q", v.String())
	case reflect.Bool:
		return fmt.Sprintf("%v", v.Bool())
	case reflect.Int, reflect.Int32, reflect.Int64:
		if v.Type() == reflect.TypeOf(time.Duration(0)) {
			return fmt.Sprintf("%q", time.Duration(v.Int()).String())
		}
		return fmt.Sprintf("%d", v.Int())
	case reflect.Slice:
		if v.Len() == 0 {
			return "[]"
		}
		parts := make([]string, v.Len())
		for i := 0; i < v.Len(); i++ {
			parts[i] = yamlValue(v.Index(i))
		}
		return "[" + strings.Join(parts, ", ") + "]"
	case reflect.Map:
		if v.Len() == 0 {
			return "{}"
		}
		keys := make([]string, 0, v.Len())
		for _, k := range v.MapKeys() {
			keys = append(keys, fmt.Sprintf("%v", k.Interface()))
		}
		sort.Strings(keys)
		parts := make([]string, len(keys))
		for i, k := range keys {
			parts[i] = fmt.Sprintf("%s: %s", k, yamlValue(v.MapIndex(reflect.ValueOf(k))))
		}
		return "{" + strings.Join(parts, ", ") + "}"
	default:
		return fmt.Sprintf("%v", v.Interface())
	}
}
